admin:
  password: '{cipher}AYAfdzcrkjwM4rt2jhkxezO5zBNmfljIeeBFXKsUMV8Q9ASYjBCv2lBtu2L7Se7hEK7DTDc1JxTmkiZW6dn14UhEdbpcSObqknAxiaK7wMBz3e6POdTZeIF1J/kCwBSvccEUGZuog1eZjQav14uE5wYQqyDfqnOPvak4JndzykJBjZ4SSzZNwOUYxQyRaA0gQbgYF+E+ZnY7BpwzfcT2DTpaZDPAYUBLFiCiY6bNbLBC3LS3i/Qq0/cv6OOz1Wl6ruwTQBrIHyrUiHOnbuj7MvBtl+VvaMyFaIFuxTDXZ7YxuxR4+l2Nd3eCqD2VDD63OrMlBWkcdBSJXOttIecqc+plciKAGdd4B8NIE/aD2oYChXKU/HDOyj6AoxJSSCjhGOBsa7T0j0w4ecqBwXNx8T9rp6fLpZxVWMZsJ53wcg2DfkbZSU2ZPeqYoCijK604HOVPDU8CcS1Rskj0wXrllvQRfXk0gt5PaVdlPCfKfMMX1fZKeglXtkYxMb5heyvpZsgy3Kl5VPXhjAcCatdKNrA/mMUwL8Bv2toFaBENp1nqIg=='

config:
  server:
    url: https://local.codzs.com:5002
  password: '{cipher}AYAfdzcrkjwM4rt2jhkxezO5zBNmfljIeeBFXKsUMV8Q9ASYjBCv2lBtu2L7Se7hEK7DTDc1JxTmkiZW6dn14UhEdbpcSObqknAxiaK7wMBz3e6POdTZeIF1J/kCwBSvccEUGZuog1eZjQav14uE5wYQqyDfqnOPvak4JndzykJBjZ4SSzZNwOUYxQyRaA0gQbgYF+E+ZnY7BpwzfcT2DTpaZDPAYUBLFiCiY6bNbLBC3LS3i/Qq0/cv6OOz1Wl6ruwTQBrIHyrUiHOnbuj7MvBtl+VvaMyFaIFuxTDXZ7YxuxR4+l2Nd3eCqD2VDD63OrMlBWkcdBSJXOttIecqc+plciKAGdd4B8NIE/aD2oYChXKU/HDOyj6AoxJSSCjhGOBsa7T0j0w4ecqBwXNx8T9rp6fLpZxVWMZsJ53wcg2DfkbZSU2ZPeqYoCijK604HOVPDU8CcS1Rskj0wXrllvQRfXk0gt5PaVdlPCfKfMMX1fZKeglXtkYxMb5heyvpZsgy3Kl5VPXhjAcCatdKNrA/mMUwL8Bv2toFaBENp1nqIg=='

authorization:
  server:
    url: https://local.codzs.com:5003

# server:
#   ssl:
#     keystore: ./../java-codzs-resource/local/local.codzs.com.p12
#     password: localpassword

spring:
  boot:
    admin:
      client:
        url: https://local.codzs.com:5001
        password: '{cipher}AYAfdzcrkjwM4rt2jhkxezO5zBNmfljIeeBFXKsUMV8Q9ASYjBCv2lBtu2L7Se7hEK7DTDc1JxTmkiZW6dn14UhEdbpcSObqknAxiaK7wMBz3e6POdTZeIF1J/kCwBSvccEUGZuog1eZjQav14uE5wYQqyDfqnOPvak4JndzykJBjZ4SSzZNwOUYxQyRaA0gQbgYF+E+ZnY7BpwzfcT2DTpaZDPAYUBLFiCiY6bNbLBC3LS3i/Qq0/cv6OOz1Wl6ruwTQBrIHyrUiHOnbuj7MvBtl+VvaMyFaIFuxTDXZ7YxuxR4+l2Nd3eCqD2VDD63OrMlBWkcdBSJXOttIecqc+plciKAGdd4B8NIE/aD2oYChXKU/HDOyj6AoxJSSCjhGOBsa7T0j0w4ecqBwXNx8T9rp6fLpZxVWMZsJ53wcg2DfkbZSU2ZPeqYoCijK604HOVPDU8CcS1Rskj0wXrllvQRfXk0gt5PaVdlPCfKfMMX1fZKeglXtkYxMb5heyvpZsgy3Kl5VPXhjAcCatdKNrA/mMUwL8Bv2toFaBENp1nqIg=='

codzs:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: '{cipher}AYBZTs8B9RuGMhgG00sG+OL7z9EYZh7OHBW90yyr91ve7d50s2+a1lgfCqK+gY4+zsiyOD/WFRAIusIh+e5GFqzBwVVz2k/s702es1HUj4+Ssr/35nOxfcI3FNcWLTCgEuiH6GClUGVZxi5ZP7NUYlPIfOx7n2XQ2dELk0WQ9F3GxAWhhGNLWpAS6BYoS1g5Kn2QDJ+fcRsmIaJkFoV1z4TYw8e/1KP05n+pUpuE017LBM7CW8N6GeUbCWzBp/9OXFWcqlMkHWTLwZhbjg1DZeG5Ro8bF58nBGkaSIpPN2R72JbIBPoG023qw/pl6S9U4kqmAdBBbDZHXnGJwGzJjV9r57udo7l3Cmppe2k1pVljaXPLEs74vl8M7bSG64MLrJ1N5YBf0Z2o7sveFNsuCYXAGuIld5uCZ5+T9Vnce0MGgORrJ6RbqgLo5dnWy43zZmkBvACJ50Vkm/CFNRtz/CG/VFg3xNC/ZVwO0dNCzbH2fPHq0EX+vwzPcVlU0r3r30VW77+tV+uQLY0GncDTrYcRki68rL0y3rmh7S55crdDhQ=='
  redis:
    host: localhost
    port: 6379
