spring:
  # Security configuration for management endpoints
  security:
    user:
      password: ${MANAGEMENT_PASSWORD:password}
      name: ${MANAGEMENT_USER:user1}
      roles: ACTUATOR
  boot:
    admin:
      client:
        url: https://local.codzs.com:5001
        username: admin-service-user
        password: ${admin.password}

# Start: Exception handling
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
    include-message: always
# End: Exception handling

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "health,info,metrics,loggers,configprops"  # Only expose safe endpoints for admin server
        exclude: "env,heapdump,threaddump,shutdown,beans"  # Exclude dangerous endpoints
    loggers:
      enabled: true
    health:
      validate-group-membership: false
      group:
        db:
          include: db

  health:
    db:
      enabled: true
    elasticsearch:
      enabled: true
    mongo:
      enabled: true
    redis:
      enabled: true

  security:
    enabled: true

  info:
    env:
      enabled: true
    git:
      mode: full

# Start: OpenApi
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: false
  use-management-port: false
# End: OpenApi

# Start: Enable SSL on localhost
server:
  ssl:
    key-store: ${server.ssl.keystore}
    key-store-password: ${server.ssl.password}
    key-store-type: pkcs12
    key-password: ${server.ssl.password}
# End: Enable SSL on localhost
