spring:
  boot:
    admin:
      client:
        username: admin-service-user
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}

# Start: Exception handling
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
    include-message: always
# End: Exception handling

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"
    loggers:
      enabled: true
    health:
      validate-group-membership: false
      group:
        db:
          include: db

  health:
    db:
      enabled: true
    elasticsearch:
      enabled: true
    mongo:
      enabled: true
    redis:
      enabled: true

  security:
    enabled: true

  info:
    env:
      enabled: true
    git:
      mode: full

# Start: OpenApi
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: true
  use-management-port: true
# End: OpenApi
