spring:
  boot:
    admin:
      client:
        url: https://dev.localhost.com:5001
        username: admin-service-user
        password: '{cipher}AYCAdc8PaL5XHnmtxx602kzHwapj09i2tG7y6PzrL3qnDWcN12YnxgD2FLl/xkZrHUl+CgwyIANbjbughAb7W8Di3JJvEUbK+PIcpqANzqvbtT/ZFjQ3SkxH3x0Uyrw+ykH+eMaI/PMsuKJqvkBrZ6Fj8LilTlRRBPZZQg+ZX5hYa6WvJ07i/l6acZ1R6TeuaZfowXcy88tAODIMd1+k4pVbHjiXD5ET68Z/qk35Ej8cra2P6CLsfMeBGezQororAwAp2fM3u54nnYMDqPlC32vQPW9WpPh3vHM6jloy165FUMhBeuPm1jZeoXu8OIaafta5V0xNLnG1GFdUxgbThZMtlITExgUj08KE/GYKXndSQXt6qSvCZ7kfjJru3EpZBBlRFPkFV3wnscOHYA3tRil5UXANJ3HQ2bNmR6r3Z7V8OZzxFU3budRaWUbdSfZIKeismnWNtGZ9lMh0TG5HNqqugbTbxNeZJTskIhRyBKaOfYG2ovBqWVa1+l6gYQVHOErDFXr2mDY08uMQbaSNm5/tC9PnHN+xjZEtC3zJ5WL1fA=='
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"
    loggers:
      enabled: true
    health:
      validate-group-membership: false
      group:
        db:
          include: db

  health:
    db:
      enabled: true
    elasticsearch:
      enabled: true
    mongo:
      enabled: true
    redis:
      enabled: true

  server:
    ssl:
      enabled: false
#      key-store: classpath:management.jks
#      key-password: secret

  security:
    enabled: true

  info:
    env:
      enabled: true
    git:
      mode: full

# Start: OpenApi
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: true
  use-management-port: true
# End: OpenApi

# Start: Enable SSL on localhost
server:
  ssl:
    key-store: ${server.ssl.keystore} #classpath:dev.localhost.com.p12
    key-store-password: cerpassword
    key-store-type: pkcs12
    key-password: cerpassword
# End: Enable SSL on localhost
