spring:
  boot:
    admin:
      client:
        instance:
          management-base-url: ${management.server.base.url}

  security:
    oauth2:
      client:
        registration:
          articles-client-oidc:
            provider: spring
            client-id: articles-client
            client-secret: ${oauth2.client.article.secret}
            authorization-grant-type: authorization_code
            redirect-uri: "${my.url}/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: articles-client-oidc
          articles-client-authorization-code:
            provider: spring
            client-id: articles-client
            client-secret: ${oauth2.client.article.secret}
            authorization-grant-type: authorization_code
            redirect-uri: "${my.url}/authorized"
            scope: articles.read
            client-name: articles-client-authorization-code
        provider:
          spring:
            issuer-uri: ${authorization.server.url}

  data:
    redis:
      host: ${redis.server.host}
      port: ${redis.server.port}

external:
  property: application.yml in java-client-resource-service