spring:
  data:
    redis:
      host: ${codzs.redis.host}
      port: ${codzs.redis.port}

  security:
    oauth2:
      client:
        registration:
          articles-client-oidc:
            provider: spring
            client-id: articles-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "https://local.codzs.com:8001/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: articles-client-oidc
          articles-client-authorization-code:
            provider: spring
            client-id: articles-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "https://local.codzs.com:8001/login/oauth2/code/articles-client-authorization-code"
            scope: articles.read
            client-name: articles-client-authorization-code
        provider:
          spring:
            issuer-uri: ${authorization.server.url}

resource:
  server:
    url: https://local.codzs.com:8002

platform:
  type: AWS_EC2_INSTANCE

external:
  property: application.yml in java-client-resource-service