my:
  url: https://local.codzs.com:${server.port}

management:
  server:
    base:
      url: https://local.codzs.com:${management.server.port}

# Redis Session Configuration for Client Resource Service
spring:
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis
    redis:
      namespace: "client-resource-service:sessions"
      flush-mode: on_save
      save-mode: on_set_attribute
    timeout: 30m
