spring:
  boot:
    admin:
      client:
        instance:
          management-base-url: ${management.server.base.url}
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${authorization.mysql.host}:${authorization.mysql.port}/authorization
    username: ${authorization.mysql.username}
    password: ${authorization.mysql.password}

  session:
    store-type: redis
    redis:
      namespace: "authorization-service:sessions"
      flush-mode: on_save
      save-mode: on_set_attribute
    timeout: 30m

  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${google.client_id.prod}
            client-secret: ${google.client_secret.prod}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: ${github.client_id.prod}
            client-secret: ${github.client_secret.prod}
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login

management:
  server:
    base:
      url: https://local.codzs.com:${management.server.port}
  jpa:
    generate-ddl: false
  data:
    redis:
      host: ${authorization.redis.host}
      port: ${authorization.redis.port}

hibernate:
  show_sql: false

acl:
  redis:
    cache:
      key: com.codzs.acl.cache.local

platform:
  type: AWS_EC2_INSTANCE


server:
  servlet:
    session:
      cookie:
        name: AUTHSESSIONID
        path: /
        secure: true
        http-only: true
        same-site: none
      timeout: 30m

app:
  security:
    hsts:
      max-age-seconds: 63072000
      include-sub-domains: true
    csp:
      default-src: "'self'"
      script-src: "'self' https://cdn.jsdelivr.net"
      style-src: "'self' https://cdn.jsdelivr.net"
      img-src: "'self' data:"
      font-src: "'self' https://cdn.jsdelivr.net"
      form-action: "'self'"
      base-uri: "'self'"
      connect-src: "'self'"
    device-cors:
      allowed-origins:
        - "https://production.codzs.com:4200"
        - "https://production.codzs.com:8001"
        - "https://production.codzs.com:8004"
        - "https://production.codzs.com:5002"
      allowed-headers:
        - "Content-Type"
        - "Authorization"
        - "X-Requested-With"
      allowed-methods:
        - "GET"
        - "POST"
        - "OPTIONS"
      allow-credentials: true
      max-age-seconds: 3600
  cors:
    allowed-origins: "https://production.codzs.com:4200,https://production.codzs.com:5002"
    allow-credentials: true


device:
  security:
    rate-limiting:
      enabled: true
      requests-per-minute: 5
      time-window-minutes: 1

security:
  ip-blacklist:
    enabled: true
    block-response-delay-ms: 2000
  ip-whitelist:
    enabled: true
    block-response-delay-ms: 2000
    enforce-mode: true

resilience4j:
  ratelimiter:
    instances:
      device-authorization:
        limit-for-period: 5
        limit-refresh-period: 60s
        timeout-duration: 200ms
        register-health-indicator: true
        event-consumer-buffer-size: 50
    metrics:
      enabled: true
      distribution-statistic-expiry: 2m
      distribution-statistic-buffer-size: 50