authorization:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: '{cipher}AYBZTs8B9RuGMhgG00sG+OL7z9EYZh7OHBW90yyr91ve7d50s2+a1lgfCqK+gY4+zsiyOD/WFRAIusIh+e5GFqzBwVVz2k/s702es1HUj4+Ssr/35nOxfcI3FNcWLTCgEuiH6GClUGVZxi5ZP7NUYlPIfOx7n2XQ2dELk0WQ9F3GxAWhhGNLWpAS6BYoS1g5Kn2QDJ+fcRsmIaJkFoV1z4TYw8e/1KP05n+pUpuE017LBM7CW8N6GeUbCWzBp/9OXFWcqlMkHWTLwZhbjg1DZeG5Ro8bF58nBGkaSIpPN2R72JbIBPoG023qw/pl6S9U4kqmAdBBbDZHXnGJwGzJjV9r57udo7l3Cmppe2k1pVljaXPLEs74vl8M7bSG64MLrJ1N5YBf0Z2o7sveFNsuCYXAGuIld5uCZ5+T9Vnce0MGgORrJ6RbqgLo5dnWy43zZmkBvACJ50Vkm/CFNRtz/CG/VFg3xNC/ZVwO0dNCzbH2fPHq0EX+vwzPcVlU0r3r30VW77+tV+uQLY0GncDTrYcRki68rL0y3rmh7S55crdDhQ=='
  redis:
    host: localhost
    port: 6379

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${authorization.mysql.host}:${authorization.mysql.port}/authorization
    username: ${authorization.mysql.username}
    password: ${authorization.mysql.password}
  session:
    store-type: redis
    redis:
      namespace: "authorization-service:sessions"
      flush-mode: on_save
      save-mode: on_set_attribute
    timeout: 30m
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${google.client_id}
            client-secret: ${google.client_secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: ${github.client_id}
            client-secret: ${github.client_secret}
            scope: user:email, read:user
            client-name: Sign in with GitHub
          google:
            client-id: ${google.client_id}
            client-secret: ${google.client_secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github:
            client-id: ${github.client_id}
            client-secret: ${github.client_secret}
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login

management:
  server:
    base:
      url: https://local.codzs.com:${management.server.port}

hibernate:
  show_sql: true

device:
  security:
    rate-limiting:
      enabled: true
      requests-per-minute: 10
      time-window-minutes: 1

security:
  ip-blacklist:
    enabled: true
    block-response-delay-ms: 1000
  ip-whitelist:
    enabled: true
    block-response-delay-ms: 1000
    enforce-mode: false

app:
  security:
    hsts:
      max-age-seconds: 31536000
      include-sub-domains: true
    csp:
      default-src: "'self'"
      script-src: "'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net"
      style-src: "'self' 'unsafe-inline' https://cdn.jsdelivr.net"
      img-src: "'self' data: https:"
      font-src: "'self' https://cdn.jsdelivr.net"
      form-action: "'self'"
      base-uri: "'self'"
      connect-src: "'self' https://local.codzs.com:*"
    device-cors:
      allowed-origins:
        - "https://local.codzs.com:4200"
        - "https://local.codzs.com:8001"
        - "https://local.codzs.com:8004"
        - "https://local.codzs.com:5002"
        - "http://localhost:4200"
        - "http://127.0.0.1:4200"
      allowed-headers:
        - "Content-Type"
        - "Authorization"
        - "X-Requested-With"
        - "X-XSRF-TOKEN"
      allowed-methods:
        - "GET"
        - "POST"
        - "OPTIONS"
      allow-credentials: true
      max-age-seconds: 1800
  cors:
    allowed-origins: "http://localhost:4200,http://127.0.0.1:4200,https://local.codzs.com:4200,https://local.codzs.com:5002"
    allow-credentials: true

resilience4j:
  ratelimiter:
    instances:
      device-authorization:
        limit-for-period: 10
        limit-refresh-period: 60s
        timeout-duration: 100ms
        register-health-indicator: true
        event-consumer-buffer-size: 100
    metrics:
      enabled: true
      distribution-statistic-expiry: 1m
      distribution-statistic-buffer-size: 100
