spring:
  boot:
    admin:
      client:
        instance:
          management-base-url: ${management.server.base.url}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${authorization.mysql.host}:${authorization.mysql.port}/authorization
    username: ${authorization.mysql.username}
    password: ${authorization.mysql.password}
  jpa:
    generate-ddl: false
  data:
    redis:
      host: ${authorization.redis.host}
      port: ${authorization.redis.port}

hibernate:
  show_sql: true

acl:
  redis:
    cache:
      key: com.codzs.acl.cache.local

external:
  property: application-dev.yml inside java-demo-app