spring:
  boot:
    admin:
      client:
        instance:
          management-base-url: ${management.server.base.url}
          metadata:
            user:
              name: authorization-service-user
              password: ${authorization.password}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${authorization.mysql.host}:${authorization.mysql.port}/authorization
    username: ${authorization.mysql.username}
    password: ${authorization.mysql.password}

management:
  server:
    base:
      url: https://local.codzs.com:${management.server.port}
  jpa:
    generate-ddl: false
  data:
    redis:
      host: ${authorization.redis.host}
      port: ${authorization.redis.port}

hibernate:
  show_sql: true

acl:
  redis:
    cache:
      key: com.codzs.acl.cache.local

platform:
  type: AWS_EC2_INSTANCE

external:
  property: application-dev.yml inside java-demo-app

server:
  servlet:
    session:
      cookie:
        name: AUTHSESSIONID
        path: /
        secure: true
        http-only: true
        same-site: none
      timeout: 30m