resource:
  server:
    url: https://local.codzs.com:8002
    secret: '{cipher}AYAX0pA40tBtGcaWbhzyRnST9abfFgsm+NFiIOX7cFjXIWBO/IKMi8+pcAA0iXPoCSSaWWqjZA/O++PXR29PKzMSP7fosr1DU8yIQnHzi44299AD2BYOdgQlpSob1gc+A8qPoTwYzsGbK3vuq4wyeSeY6mBb6rOB9kJKSKsGbBcIRvcWKEtegxeoDiCa5wMJXjvngFM0+sEla2Q3XLQEj8r110k1k6wFZaZv2K2xHJuqhqBC4eZ5CWkIy1y/oP3kKAEZvRk3tSiK12TlGeW7naNCxmISaULRpmPZS2s9jTVwSNaT2NP6vDV8ZDY9cwiP8PTz+vHe82/2YWTttO8HLQlFAcXaDKzSxco1eMlb97sBGJsgSk1SjKBLJef7VemI9zyMrqJezWekNn140YIyLe1GxWG9G1v2zaiFDaXfZV8rTYksJuHwzJBr3B1Rt6QoaZZyPcOV2IhOUURNU/w0f5JzSEZmTl54D7pdC77C6u1xRHT/7QEIlzGp6LGhthgDMxB/GLrj/xzZ87Hl/UL3JyyR6uIhj1hq5RxhToiYiIGr7A=='

resource-client:
  server:
    url: https://local.codzs.com:8001