spring:
  boot:
    admin:
      client:
        instance:
          management-base-url: ${management.server.base.url}
          metadata:
            user:
              name: resource-service-user
              password: ${resource.server.secret}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${authorization.server.url}

platform:
  type: AWS_EC2_INSTANCE

external:
  property: application.yml in java-resource-service