spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${authorization.server.url}

platform:
  type: AWS_EC2_INSTANCE

external:
  property: application.yml in java-resource-service