spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${oauth2.resource.server.jwt.issuer.uri}

  boot:
    admin:
      client:
        instance:
          management-base-url: ${management.server.base.url}

external:
  property: application.yml in java-resource-service