spring:
  boot:
    admin:
      client:
        instance:
          management-base-url: ${management.server.base.url}
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}

app:
  base-uri: http://127.0.0.1:4200

management:
  server:
    base:
      url: https://local.codzs.com:${management.server.port}

platform:
  type: AWS_EC2_INSTANCE

external:
  property: application.yml in java-bff-service


# Enable detailed OAuth2 debugging
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.boot.web.client: DEBUG
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.oauth2.client.endpoint: TRACE