authorization:
  server:
    url: https://local.codzs.com:5003

service:
  endpoints:
    authServerLogoutUrl: https://local.codzs.com:5003/logout
    authServerUserinfoUrl: https://local.codzs.com:5003/userinfo
    messagesUrl: https://local.codzs.com:8002/messages

management:
  server:
    base:
      url: https://local.codzs.com:${management.server.port}

spring:
  data:
    redis:
      host: ${codzs.redis.host}
      port: ${codzs.redis.port}
  session:
    store-type: redis
    redis:
      namespace: "bff-service:sessions"
      flush-mode: on_save
      save-mode: on_set_attribute
    timeout: 30m

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.boot.web.client: DEBUG
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.oauth2.client.endpoint: TRACE