spring:
  boot:
    admin:
      client:
        instance:
          management-base-url: ${management.server.base.url}
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}

app:
  base-uri: http://127.0.0.1:4200
  # Security: Define allowed redirect hosts to prevent open redirect attacks
  allowed-redirect-hosts:
    - 127.0.0.1
    - localhost
    - local.codzs.com

management:
  server:
    base:
      url: https://local.codzs.com:${management.server.port}

platform:
  type: AWS_EC2_INSTANCE

external:
  property: application.yml in java-bff-service


# Production-safe logging configuration
logging:
  level:
    org.springframework.security: WARN  # Security: Prevent token exposure
    org.springframework.security.oauth2: WARN  # Security: Prevent OAuth2 token logging
    org.springframework.security.web: WARN  # Security: Prevent sensitive web details
    org.springframework.web.client: WARN  # Security: Prevent request/response logging
    org.springframework.boot.web.client: WARN  # Security: Prevent client details logging
    org.springframework.security.oauth2.client: WARN  # Security: Prevent client secret exposure
    org.springframework.security.oauth2.client.endpoint: WARN  # Security: Prevent endpoint details