authorization:
  server:
    url: https://local.codzs.com:5003

management:
  server:
    base:
      url: https://local.codzs.com:${management.server.port}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.boot.web.client: DEBUG
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.oauth2.client.endpoint: TRACE